[build]
target = "thumbv7em-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-run --chip STM32F405rgt"
runner = "arm-none-eabi-gdb -q -x openocd.gdb"

[target.thumbv7em-none-eabihf]
rustflags = [ "-C", "link-arg=-Tlink.x", ]
